apiVersion : apps/v1
kind: Deployment
metadata:
  name: dotnetmicroservices 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetmicroservices
  template:
    metadata:
      labels:
        app: dotnetmicroservices 
    spec:
      containers:
        - name: dotnetmicroservices 
          image: harpreetregistry.azurecr.io/harpreetsingh18/dotnetmicroservices:1593
          imagePullPolicy: Always
          ports:
          - containerPort: 80
